# Language flags.
language: rust

# OS matrix.
os:
  - linux
  - osx
  - windows

# Version matrix.
rust:
  - stable
  - beta
  - nightly

# Custom scripts.
script:
  - cargo build --verbose --all --all-features
  - cargo test --verbose --all --all-features

# Matrix modifications.
matrix:

  # Failures to allow.
  allow_failures:
    - rust: nightly

  # Additional builds.
  include:

    # Clippy linting.
    - rust: stable
      os: linux
      script:
        - rustup component add clippy
        - cargo clippy --all --all-features --profile test

    # Format linting.
    - rust: stable
      os: linux
      script:
        - rustup component add rustfmt
        - cargo fmt --all --all-features -- --check

    - # Test coverage.
    - rust: nightly
      os: linux
      script:
        - cargo install cargo-tarpaulin
        - cargo tarpaulin --all --all-features --ignore-tests -o Stdout

# Cargo package caching.
cache:
  cargo: true
