# Language flags.
language: rust

# OS matrix.
os:
  - linux
  - osx
  - windows

# Version matrix.
rust:
  - stable
  - beta
  - nightly

# Matrix modifications.
matrix:

  # Failures to allow.
  allow_failures:
    - rust: nightly

  # Additional builds.
  include:

    # Clippy linting.
    - rust: stable
      os: linux
      script:
        - rustup component add clippy
        - cargo clippy --all --profile test

    # Format linting.
    - rust: stable
      os: linux
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check

# Cargo package caching.
cache:
  cargo: true
